/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package elab.tampilan;

import elab.entity.Tugas;
import elab.entity.WorkDone;
import elab.model.DownloadTugasModel;
import elab.model.TugasModel;
import elab.model.WorkDoneModel;
import java.awt.Dimension;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Julian Dwi Putra
 */
public class TampilanTask extends javax.swing.JFrame {
    String id_jadwal_mapel, niss, id_tugas;
    /**
     * Creates new form TampilanTask
     */
    public TampilanTask() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_deadline = new javax.swing.JLabel();
        txt_judulTask = new javax.swing.JLabel();
        txt_deskripsi = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btn_file1 = new javax.swing.JButton();
        btn_file2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btn_kirimFile = new javax.swing.JButton();
        btn_done = new javax.swing.JButton();
        tx_id_jadwal_mapel = new javax.swing.JLabel();
        txt_status_tugas = new javax.swing.JLabel();
        btn_back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txt_deadline.setText("Deadline tugas 09-09-2020");

        txt_judulTask.setText("Judul tugas");

        txt_deskripsi.setText("Deskripsi");
        txt_deskripsi.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        txt_deskripsi.setAutoscrolls(true);

        jLabel1.setText("Attachments");

        btn_file1.setText("File 1");
        btn_file1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_file1ActionPerformed(evt);
            }
        });

        btn_file2.setText("File 2");

        jLabel2.setText("Tugas anda");
        jLabel2.setToolTipText("");

        btn_kirimFile.setText("Kirim file");
        btn_kirimFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kirimFileActionPerformed(evt);
            }
        });

        btn_done.setText("Tandai sudah selesai");
        btn_done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_doneActionPerformed(evt);
            }
        });

        tx_id_jadwal_mapel.setText("jLabel3");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_kirimFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_done, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(tx_id_jadwal_mapel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_kirimFile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_done)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tx_id_jadwal_mapel)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        txt_status_tugas.setText("Status : Not Done");

        btn_back.setText("Back");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_file1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_file2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_deskripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_judulTask, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btn_back)
                                .addGap(18, 18, 18)
                                .addComponent(txt_deadline, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_status_tugas, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_deadline, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_status_tugas)
                    .addComponent(btn_back))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_judulTask, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(txt_deskripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_file1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_file2)
                        .addContainerGap(25, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_doneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_doneActionPerformed
        WorkDone w = new WorkDone();
        WorkDoneModel workDoneModel = new WorkDoneModel();
        
        w = workDoneModel.getWork(niss, id_tugas);
        if(w.getStatus().equals("Done")){
            workDoneModel.UpdateWork("Not Done", niss, id_tugas);
            workDoneModel.UpdateTugas("Not Done", id_tugas);
            txt_status_tugas.setText("Status : Not Done");
            btn_done.setText("Turn In");
        }else if(w.getStatus().equals("Not Done")){
            workDoneModel.UpdateWork("Done", niss, id_tugas);
            workDoneModel.UpdateTugas("Done", id_tugas);
            txt_status_tugas.setText("Status : Done");
            btn_done.setText("Turn Off");
        }
    }//GEN-LAST:event_btn_doneActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        dispose();
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_file1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_file1ActionPerformed
        DownloadTugasModel downloadTugasModel = new DownloadTugasModel();
        downloadTugasModel.downloadFile_1();
    }//GEN-LAST:event_btn_file1ActionPerformed

    private void btn_kirimFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kirimFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_kirimFileActionPerformed

    /**
     * @param args the command line arguments
     */
    public void setId_jadwal_mapel(String id_jadwal, String nis){
        tx_id_jadwal_mapel.setText(id_jadwal);
        id_jadwal_mapel = tx_id_jadwal_mapel.getText();
        niss = nis;
        tx_id_jadwal_mapel.setVisible(false);
        getTugas();
       
    }
   
    private void getTugas() {
        Tugas t = new Tugas();
        TugasModel tm = new TugasModel();
        
        t = tm.getTugas(id_jadwal_mapel);
        id_tugas = t.getId_tugas();
        WorkDone w = new WorkDone();
        WorkDoneModel workDoneModel = new WorkDoneModel();
        
        w = workDoneModel.getWork(niss, id_tugas);
        if(w == null){
            workDoneModel.InsertWork(niss, id_tugas, "Not Done");
            w = workDoneModel.getWork(niss, id_tugas);
            
            if (w.getStatus().equals("Done")) {
            txt_status_tugas.setText("Status : Done");
            btn_done.setText("Turn Off");
            }else{
            txt_status_tugas.setText("Status : Not Done");
            btn_done.setText("Turn In");
            }
            if (t != null) {
            txt_deskripsi.setPreferredSize(new Dimension(250,159));
            txt_deadline.setText("Deadline tugas "+t.getDue_date());
            txt_judulTask.setText(t.getTitle());
            txt_deskripsi.setText(t.getDescription());
            txt_status_tugas.setText("Status : "+t.getStatus());
            }else{
            txt_deadline.setText("no tugas");
          }
        }else{
            if (w.getStatus().equals("Done")) {
            txt_status_tugas.setText("Status : Done");
            btn_done.setText("Turn Off");
            }else{
            txt_status_tugas.setText("Status : Not Done");
            btn_done.setText("Turn In");
            }
            if (t != null) {
            txt_deskripsi.setPreferredSize(new Dimension(250,159));
            txt_deadline.setText("Deadline tugas "+t.getDue_date());
            txt_judulTask.setText(t.getTitle());
            txt_deskripsi.setText(t.getDescription());
            txt_status_tugas.setText("Status : "+t.getStatus());
            }else{
            txt_deadline.setText("no tugas");
          }
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TampilanTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TampilanTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TampilanTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TampilanTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TampilanTask().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_done;
    private javax.swing.JButton btn_file1;
    private javax.swing.JButton btn_file2;
    private javax.swing.JButton btn_kirimFile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel tx_id_jadwal_mapel;
    private javax.swing.JLabel txt_deadline;
    private javax.swing.JLabel txt_deskripsi;
    private javax.swing.JLabel txt_judulTask;
    private javax.swing.JLabel txt_status_tugas;
    // End of variables declaration//GEN-END:variables

    
}
